# Generated by Django 4.2.30 on 2026-07-21 02:11

import apps.certificates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_category_options_remove_course_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/', verbose_name='背景图片')),
                ('content_template', models.TextField(default='培训合格证书\n\n{username} 同学：\n\n您已完成《{course_title}》培训课程的学习，\n综合成绩：{score} 分，\n特发此证，以资鼓励。\n\n颁发日期：{date}\n证书编号：{cert_no}\n', verbose_name='内容模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '证书模板',
                'verbose_name_plural': '证书模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_no', models.CharField(default=apps.certificates.models.generate_cert_no, max_length=50, unique=True, verbose_name='证书编号')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成绩')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='颁发时间')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='撤销原因')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='课程')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.certificatetemplate', verbose_name='证书模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'ordering': ['-issued_at'],
            },
        ),
    ]
