# Generated by Django 4.2.30 on 2026-07-21 02:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_category_options_remove_course_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('general', '基础配置'), ('training', '培训配置'), ('exam', '考试配置'), ('certificate', '证书配置'), ('security', '安全配置')], max_length=20, verbose_name='配置分组')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('float', '浮点数'), ('boolean', '布尔'), ('json', 'JSON')], default='string', max_length=20, verbose_name='值类型')),
                ('label', models.CharField(max_length=200, verbose_name='配置标签')),
                ('description', models.TextField(blank=True, default='', verbose_name='配置说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ScoreWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_weight', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='视频学习进度权重(%)')),
                ('material_weight', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='资料学习权重(%)')),
                ('exam_weight', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='考试成绩权重(%)')),
                ('video_threshold', models.PositiveIntegerField(default=95, help_text='视频进度达到此值视为学完', verbose_name='视频完成阈值(%)')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='及格分数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_weight', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '成绩权重配置',
                'verbose_name_plural': '成绩权重配置',
            },
        ),
    ]
