# Generated by Django 4.2.30 on 2026-08-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_category_options_remove_course_is_published_and_more'),
        ('users', '0003_user_force_password_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='如：药物警戒部培训矩阵', max_length=200, verbose_name='矩阵名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_matrices', to='users.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '培训矩阵',
                'verbose_name_plural': '培训矩阵',
                'ordering': ['department__name', 'title'],
                'unique_together': {('department', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TrainingMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='', help_text='指定岗位（留空表示部门全员必修）', max_length=100, verbose_name='岗位')),
                ('is_required', models.BooleanField(default=True, verbose_name='必修')),
                ('required_months', models.PositiveIntegerField(default=3, help_text='入职/分配后要求完成的月数', verbose_name='要求完成月数')),
                ('priority', models.IntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], default=2, verbose_name='优先级')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_items', to='courses.course', verbose_name='课程')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training_matrix.trainingmatrix', verbose_name='所属矩阵')),
            ],
            options={
                'verbose_name': '矩阵条目',
                'verbose_name_plural': '矩阵条目',
                'ordering': ['matrix', 'order', 'priority', 'id'],
                'unique_together': {('matrix', 'course', 'position')},
            },
        ),
        migrations.CreateModel(
            name='UserMatrixProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '学习中'), ('completed', '已完成'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('course_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_progress_records', to='courses.courseprogress', verbose_name='课程进度')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='training_matrix.trainingmatrixitem', verbose_name='矩阵条目')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='training_matrix.trainingmatrix', verbose_name='所属矩阵')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户矩阵进度',
                'verbose_name_plural': '用户矩阵进度',
                'ordering': ['user', 'matrix', 'item__order'],
                'indexes': [models.Index(fields=['user', 'matrix'], name='training_ma_user_id_ad99c6_idx'), models.Index(fields=['user', 'status'], name='training_ma_user_id_667610_idx')],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
