# Generated by Django 4.2.30 on 2026-06-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='课程描述')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='课程分类')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('file_type', models.CharField(choices=[('ppt', 'PPT课件'), ('word', 'Word文档'), ('pdf', 'PDF文档'), ('video', '视频')], default='pdf', max_length=20, verbose_name='资料类型')),
                ('file', models.FileField(upload_to='courses/materials/%Y/%m/', verbose_name='资料文件')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('description', models.TextField(blank=True, default='', verbose_name='资料描述')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料',
                'ordering': ['-upload_time'],
            },
        ),
    ]
