# Generated by Django 4.2.30 on 2026-07-21 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': '课程分类', 'verbose_name_plural': '课程分类'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='分类编码'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='course',
            name='review_note',
            field=models.TextField(blank=True, default='', verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='review_note',
            field=models.TextField(blank=True, default='', verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_progress', models.PositiveIntegerField(default=0, verbose_name='视频学习进度(%)')),
                ('video_total_duration', models.PositiveIntegerField(default=0, verbose_name='视频总时长(秒)')),
                ('video_watched_duration', models.PositiveIntegerField(default=0, verbose_name='已观看时长(秒)')),
                ('overall_progress', models.PositiveIntegerField(default=0, verbose_name='整体进度(%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='综合成绩')),
                ('score_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='成绩计算时间')),
                ('last_access_at', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.course', verbose_name='课程')),
                ('materials_viewed', models.ManyToManyField(blank=True, to='courses.coursematerial', verbose_name='已查看资料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程进度',
                'verbose_name_plural': '课程进度',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
