# Generated by Django 4.2.30 on 2026-07-21 06:36

import apps.signatures.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('exam', '考试签名'), ('checkin', '培训签到')], default='exam', max_length=20, verbose_name='签名类型')),
                ('signature_image', models.ImageField(upload_to=apps.signatures.models.signature_upload_path, verbose_name='签名图片')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='签名时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='设备信息')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联对象类型')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='签名者')),
            ],
            options={
                'verbose_name': '电子签名',
                'verbose_name_plural': '电子签名',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['signed_by', 'signature_type'], name='signatures__signed__494941_idx'), models.Index(fields=['content_type', 'object_id'], name='signatures__content_1f0e50_idx')],
            },
        ),
    ]
