# Generated by Django 4.2.30 on 2026-07-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', '仪表盘'), ('user', '用户管理'), ('course', '课程管理'), ('exam', '考试管理'), ('plan', '培训计划'), ('log', '学习记录'), ('report', '数据报表'), ('certificate', '证书管理'), ('system', '系统配置'), ('audit', '审核管理')], max_length=20, verbose_name='模块')),
                ('action', models.CharField(choices=[('view', '查看'), ('create', '创建'), ('edit', '编辑'), ('delete', '删除'), ('export', '导出'), ('audit', '审核'), ('publish', '发布')], max_length=20, verbose_name='操作')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='权限列表'),
        ),
    ]
