# Generated by Django 4.2.30 on 2026-06-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('course', '课程学习'), ('exam', '考试'), ('comprehensive', '综合')], default='course', max_length=20, verbose_name='任务类型')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('completion_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='完成用时（秒）')),
            ],
            options={
                'verbose_name': '任务分配',
                'verbose_name_plural': '任务分配',
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='计划描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('courses', models.ManyToManyField(blank=True, related_name='training_plans', to='courses.course', verbose_name='关联课程')),
            ],
            options={
                'verbose_name': '培训计划',
                'verbose_name_plural': '培训计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
