# Generated by Django 4.2.30 on 2026-06-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('view_course', '查看课程'), ('download_material', '下载资料'), ('start_exam', '开始考试'), ('submit_exam', '提交考试'), ('complete_task', '完成任务')], max_length=30, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='用户代理')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='停留时长（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('import', '导入'), ('export', '导出'), ('assign', '分配')], max_length=20, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, choices=[('user', '用户'), ('course', '课程'), ('exam', '考试'), ('plan', '计划'), ('task', '任务')], default='', max_length=20, verbose_name='操作对象类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='操作对象ID')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
