# Generated by Django 4.2.30 on 2026-06-03 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('logs', '0001_initial'),
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_logs', to='courses.course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_logs', to='exams.exam', verbose_name='关联考试'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_logs', to='courses.coursematerial', verbose_name='关联资料'),
        ),
        migrations.AddField(
            model_name='learninglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
