# Generated by Django 4.2.30 on 2026-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglog',
            name='action_type',
            field=models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('view_course', '查看课程'), ('download_material', '下载资料'), ('start_exam', '开始考试'), ('submit_exam', '提交考试'), ('complete_task', '完成任务'), ('checkin', '培训签到'), ('sign_exam', '考试签名')], max_length=30, verbose_name='操作类型'),
        ),
    ]
