# Generated by Django 4.2.30 on 2026-06-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, default='', verbose_name='用户答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='得分')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考试标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='考试说明')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='考试时长（分钟）')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='总分')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='及格分数')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multi_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('essay', '简答题')], default='single_choice', max_length=20, verbose_name='题目类型')),
                ('option_a', models.CharField(blank=True, default='', max_length=500, verbose_name='选项A')),
                ('option_b', models.CharField(blank=True, default='', max_length=500, verbose_name='选项B')),
                ('option_c', models.CharField(blank=True, default='', max_length=500, verbose_name='选项C')),
                ('option_d', models.CharField(blank=True, default='', max_length=500, verbose_name='选项D')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('score', models.PositiveIntegerField(default=5, verbose_name='分值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='得分')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='是否及格')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('timeout', '已超时')], default='in_progress', max_length=20, verbose_name='状态')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'ordering': ['-start_time'],
            },
        ),
    ]
