# Generated by Django 4.2.30 on 2026-07-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questionbank',
            new_name='question_ba_questio_9bfeb6_idx',
            old_name='question_bank_qtype_difficulty_idx',
        ),
        migrations.RenameIndex(
            model_name='questionbank',
            new_name='question_ba_is_acti_32e609_idx',
            old_name='question_bank_active_idx',
        ),
    ]
